// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7vRqAm-dPk9PwTtvcgo7B5mELFYTuHk',
    appId: '1:189902921041:web:45fa086cd54e0e47f7c770',
    messagingSenderId: '189902921041',
    projectId: 'solar-project-6a8a9',
    authDomain: 'solar-project-6a8a9.firebaseapp.com',
    storageBucket: 'solar-project-6a8a9.appspot.com',
    measurementId: 'G-D9LERY7QGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC28hnkUszz8y9I3iVYQ6_e9TyDvNVNTlU',
    appId: '1:189902921041:android:2a3522bb1f522104f7c770',
    messagingSenderId: '189902921041',
    projectId: 'solar-project-6a8a9',
    storageBucket: 'solar-project-6a8a9.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnj_GoPjqEhJFE9iTMiAPZDj82hnEUp0I',
    appId: '1:189902921041:ios:85f6f235ce17e341f7c770',
    messagingSenderId: '189902921041',
    projectId: 'solar-project-6a8a9',
    storageBucket: 'solar-project-6a8a9.appspot.com',
    iosBundleId: 'com.solartide.app',
  );
}
