// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfDtevV8qJ5ijfIRFNEs8toahn0R4DCnA',
    appId: '1:189902921041:web:1a4d32bdb2c956a1f7c770',
    messagingSenderId: '189902921041',
    projectId: 'solar-project-6a8a9',
    authDomain: 'solar-project-6a8a9.firebaseapp.com',
    storageBucket: 'solar-project-6a8a9.appspot.com',
    measurementId: 'G-F0VHRZ8SPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2NNjG-j_f-9YaAFB1zvdhoyE34RN0slg',
    appId: '1:189902921041:android:c827d70681708840f7c770',
    messagingSenderId: '189902921041',
    projectId: 'solar-project-6a8a9',
    storageBucket: 'solar-project-6a8a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD073Os2cJFZv1ESDBkTvZVs7IkLOQRRF8',
    appId: '1:189902921041:ios:96385e548138b5aaf7c770',
    messagingSenderId: '189902921041',
    projectId: 'solar-project-6a8a9',
    storageBucket: 'solar-project-6a8a9.appspot.com',
    iosBundleId: 'com.example.solarProject',
  );
}
